<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-05-08T22:51:02Z" name="Default suite" finished-at="2019-05-08T22:51:02Z" duration-ms="76">
    <groups>
    </groups>
    <test started-at="2019-05-08T22:51:02Z" name="Default test" finished-at="2019-05-08T22:51:02Z" duration-ms="76">
      <class name="com.ct.May08Test">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="beforeMethod" finished-at="2019-05-08T22:51:02Z" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TestCase01()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="TestCase01" finished-at="2019-05-08T22:51:02Z" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase01 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="afterMethod" finished-at="2019-05-08T22:51:02Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="beforeMethod" finished-at="2019-05-08T22:51:02Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TestCase03()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="TestCase03" finished-at="2019-05-08T22:51:02Z" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [170] but found [150]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [170] but found [150]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.ct.May08Test.TestCase03(May08Test.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase03 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.ct.May08Test@5d740a0f]" started-at="2019-05-08T22:51:02Z" name="afterMethod" finished-at="2019-05-08T22:51:02Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.ct.May08Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
